/*
 * Copyright 2016 Johannes Donath <johannesd@torchmind.com>
 * and other copyright owners as documented in the project's IP log.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.torchmind.mango.concurrency.lock;

import edu.umd.cs.findbugs.annotations.NonNull;
import edu.umd.cs.findbugs.annotations.Nullable;
import java.util.Optional;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.locks.Lock;
import java.util.function.Supplier;

/**
 * Provides a few extensions to Java's locks to improve code quality when working with blocking
 * structures.
 *
 * @author <a href="mailto:johannesd@torchmind.com">Johannes Donath</a>
 */
public interface FunctionalReadLock extends FunctionalLock {

  /**
   * Creates a smart read lock instance by wrapping an existing lock.
   *
   * @param lock a lock.
   * @return a wrapped read smart lock.
   */
  @NonNull
  static FunctionalReadLock wrap(@NonNull Lock lock) {
    return new FunctionalReadLockImpl(lock);
  }

  /**
   * Acquires the lock, retrieves a value and releases the lock.
   *
   * @param supplier a supplier.
   * @param <R> a value type.
   * @return a value.
   * @see #lock() for a more specific documentation on the locking process.
   * @see #unlock() for a more specific documentation on the unlocking process.
   */
  <R> R get(@NonNull Supplier<R> supplier);

  /**
   * Acquires the lock, retrieves a value and releases the lock.
   *
   * @param supplier a supplier.
   * @param <R> a value type.
   * @return a value.
   * @throws InterruptedException when the thread is interrupted when attempting to acquire the
   * lock.
   * @see #lockInterruptibly() for a more specific documentation on the locking process.
   * @see #unlock() for a more specific documentation on the unlocking process.
   */
  <R> R getInterruptibly(@NonNull Supplier<R> supplier) throws InterruptedException;

  /**
   * Tries to acquire the lock, retrieve a value and release the lock.
   *
   * @param supplier a supplier.
   * @param <R> a value type.
   * @return a value.
   * @see #tryLock() for a more specific documentation on the locking process.
   * @see #unlock() for a more specific documentation on the unlocking process.
   */
  @NonNull
  <R> Optional<R> tryGet(@NonNull Supplier<R> supplier);

  /**
   * Tries to acquire the lock, retrieve a value and release the lock while ensuring the specified
   * amount of time is not exceeded when attempting to acquire the lock.
   *
   * @param time an amount of time to wait for holding threads to release their locks.
   * @param timeUnit a time unit.
   * @param supplier a supplier.
   * @param <R> a value type.
   * @return a value.
   * @throws InterruptedException when the thread is interrupted while attempting to acquire the
   * lock.
   * @see #tryLock(long, TimeUnit) for a more specific documentation on the locking process.
   * @see #unlock() for a more specific documentation on the unlocking process.
   */
  @NonNull
  <R> Optional<R> tryGet(long time, @NonNull TimeUnit timeUnit, @NonNull Supplier<R> supplier)
      throws InterruptedException;

  /**
   * Releases the lock and returns a passed value.
   *
   * @param value a return value.
   * @param <R> a return value type.
   * @return a value.
   * @see #unlock() for a more specific documentation on the unlocking process.
   */
  <R> R unlock(@Nullable R value);

  /**
   * Releases the lock and returns a value generated by the specified supplier.
   *
   * @param supplier a supplier.
   * @param <R> a return value type.
   * @return a value.
   * @see #unlock() for a more specific documentation on the unlocking process.
   */
  <R> R unlock(@NonNull Supplier<R> supplier);
}
